name: gcc
on: [pull_request, push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install GCC
        uses: egor-tensin/setup-gcc@v1

      - name: Compile Debug
        run: gcc -Wall -Og *.c -o luf_savic_debug

      - name: Compile Release
        run: gcc -O3 *.c -o luf_savic

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v2
        with:
          name: luf_savic-linux
          path: luf_savic

  build-windows:
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install MinGW
        uses: egor-tensin/setup-mingw@v2

      - name: Compile Debug
        run: gcc -Wall -Og *.c -o luf_savic.debug.exe

      - name: Compile Release
        run: gcc -O3 *.c -o luf_savic.exe

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v2
        with:
          name: luf_savic-windows
          path: luf_savic.exe
